### ISSUE TITLE
[ux:change] Send password reset emails using HTML theme 

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#103]
Depends on openwisp/openwisp-utils#259.

Let's see if we can find a way to send the password reset emails using the HTML theme from openwisp/openwisp-utils#259.

Looking at the code, it seems the serializer uses django-allauth under the hood:

https://github.com/openwisp/openwisp-radius/blob/c8e628d6133121c0c0c8841e4d03a18a0bf4e856/openwisp_radius/api/serializers.py#L347-L362

Which in turn calls:

https://github.com/openwisp/openwisp-radius/blob/c8e628d6133121c0c0c8841e4d03a18a0bf4e856/openwisp_radius/templates/custom_password_reset_email.html#L1-L14

So it should be similar to what @devkapilbansal is doing in https://github.com/openwisp/openwisp-users/pull/295.

**Comment by nikhanal** [comment]
Can I work on this issue?

**Comment by nemesisdesign** [comment]
@nikhanal if you're just starting out with openwisp, maybe this is a bit too advanced. Go ahead if you want, but there are many other issues listed on our [Contributor's board](https://github.com/orgs/openwisp/projects/3) which are more suited as first issues and I suggest you to look at those, thanks!
