### ISSUE TITLE
[radius/emails] Allow customizing email messages

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#104]
Allow customizing email messages sent to the users during registration and password reset.

**Comment by atb00ker** [comment]
I am assuming you mean it different email per organization, right?
i.e two new fields in organization model that ask for organization email text, which is given to the email context and put in the body.

**Comment by nemesisdesign** [comment]
This issue needs more definition.
Probably I made some confusion, the emails that get sent when the user registers are sent from django-alluauth/openwisp-users.

**Comment by nemesisdesign** [comment]
I'll just close it for now.
