### ISSUE TITLE
[bug] PostAuth view fails is password is too long

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#116]
If the password sent to the PostAuth view is too long and the authentication attempt was unsuccessful, the view fails.
I think we should prevent the failure, cutting the password and append the ellipsis unicode character (eg: `looongpasssword…`).

**Comment by atb00ker** [comment]
Can you please provide more information,
1. I am assuming by fail you mean the fact that the password overflows off the screen, as shown here:  
![screenoverflow](https://user-images.githubusercontent.com/24985760/87850619-4fe01780-c90f-11ea-8be5-16b33e981590.png)

2. At what length should I trim the password? I don't think people use OpenWISP from phone so 80 should be a good point, but please confirm this. :smile:

**Comment by nemesisdesign** [comment]
@atb00ker PostAuth API view, try to send a POST to that view with a very long token as the password, I discovered this while testing social login, the oauth token used by some social networks are very long and don't fit.

Keep in mind we don't want to store password in successful attempts but only in unsuccessful ones

**Comment by atb00ker** [comment]
Yes, I have been using the Postauth API for creating those postauth records, the password is saved for all requests requests, even the admin account in which I am providing a small correct password.

```
curl -X POST http://localhost:8000/api/v1/postauth/ \
     -H "Authorization: Bearer <org-uuid> <secret>" \
     -d "username=admin&password=admin&reply=1&called_station_id=1&calling_station_id=2"
```

Similar results for long passwords:

```
curl -X POST http://localhost:8000/api/v1/postauth/ \
     -H "Authorization: Bearer <org-uuid> <secret>" \
     -d "username=tester&password=86TD74tmKBsxbHervmkDrL7ttZBfkeDhU04mh6GGKkPLdOKEanHyILJKg9gpd8Nh2J5wV1mghGjmOobOseMi0zeEVjj0nSs7AAjk7C8i6B4M4w6wi0YmHlfLnMzXr17IHLlo70vtuFXnNNEI3De0RbVRFqD5THfx0cPt5bzaHybose6cezl1fJ6WUVlyF0FZ2SDnkrmwvlyrIAMcMdlppn03EggIs9ynQyuCw9JCXtsFJmfgRGaGVAm6Bm&reply=1&called_station_id=1&calling_station_id=2"
```

I am sure It's due to lack of knowledge that I don't understand this, I am working on it.

**Comment by nemesisdesign** [comment]
I found out why in the dev env is not failing (while it does fail in staging/prod envs): locally we use sqlite, which doesn't honor the max length of the varchar field.

Try this test:

```python
def test_postauth_long_password(self):
        from django.utils.crypto import get_random_string
        self.assertEqual(RadiusPostAuth.objects.all().count(), 0)
        params = {'username': 'molly', 'password': get_random_string(length=128), 'reply': 'Access-Reject'}
        params = self._get_postauth_params(**params)
        response = self.client.post(
            reverse('radius:postauth'), params, HTTP_AUTHORIZATION=self.auth_header
        )
        self.assertEqual(response.status_code, 201)
        self.assertEqual(response.data, None)
        self.assertEqual(
            RadiusPostAuth.objects.filter(username='molly').count(),
            1,
        )
        pa = RadiusPostAuth.objects.filter(username='molly').first()
        with self.subTest('Ensure validation does not fail'):
            pa.full_clean()
        with self.subTest('Ensure max length is honored'):
            self.assertEqual(len(pa.password), RadiusPostAuth.password.field.max_length)
```

This is how I think it should work.

Another issue: `RadiusPostAuthSerializer.validate` is not calling super, which does not execute all the validators, I think we should do this:

```python
class RadiusPostAuthSerializer(serializers.ModelSerializer):
    # ...
    def validate(self, data):
        # do not save correct passwords in clear text
        if data['reply'] == 'Access-Accept':
            data['password'] = ''
        data = super().validate(data)
        return data
```

We may also increase he max length, but it doesn't seem to be necessary.

**Comment by atb00ker** [comment]
Thanks, I understand now! 
You've practically solved the main problem for me, thank you for the help.
I've done the remaining part. :smile:
