### ISSUE TITLE
[radius/registration] Support email verification when sms verification is enabled 

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#118]
Right now when an organization has enabled the sms verification, if a user registers, no verification email will be sent.

This was a shortcut to avoid flagging the user as `is_active` if they verify their email address but not their phone number (by using the sms token verification) when signing up for a wifi service.

Eg: users sign up, they may have data active on their phone and will receive the email verification, verify the email address, skip the SMS verification, open the captive page in an incognito window and be able to login to the wifi service and pass the authentication.

We want to avoid this.

The ideal solution would be to just make sure verifying the email address does not flag the user as `is_active`.

**Comment by nemesisdesign** [comment]
@atb00ker did you create it from the admin or via the registration endpoint of the API?
I meant the registration API, which is the endpoint used by end-users to sign up for the wifi service.

**Comment by atb00ker** [comment]
Okay, so [user.is_active=False](https://github.com/openwisp/openwisp-radius/blob/d32dac0fd53ef8116cac70041828328001e37ceb/openwisp_radius/api/serializers.py#L191-#L192) causes the email to be not send.

So, I think the tasks are:
1. Send email even when `is_active` is False. (I'll find a clean way to keep the flag `False` while overriding allauth to send the mail)
2. In the validate email, remove `is_active` part if `self.is_sms_verification_enabled` is `True`.

**Comment by nemesisdesign** [comment]
This was solved
