### ISSUE TITLE
API should understand organization automatically

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#12]
At the moment it is necessary to change the configuration of freeradius to send the `organization`, but this doesn't scale well when using multiple organizations.

We can make openwisp-radius automatically figure out for which organization the request is coming from by doing something similar to what `openwisp-controller` does.

Here is a rough estimate of the things that need to be changed/added:

- a model similar to to [OrganizationConfigSettings](https://github.com/openwisp/openwisp-controller/blob/master/openwisp_controller/config/models.py#L199-L227) (eg: `OrganizationRadiusSettings`) of openwisp-controller should be added, this model must store the `token` for the freeradius API and a boolean value that indicates whether the freeradius module is active for that organization (some organization may not use it and hence it doesn't make sense to keep it enabled, it also reduces the attack surface) 
- `TokenAuthentication` needs to be extended and instead of checking the settings it should query the database, should look for the uuid and token of the organization, if not found should return `403`
- since freeradius may send many requests to the API, performing the same DB query each time for authorization would slow the system down, so we should use caching to avoid this
- the cache needs to be invalidated (partially or totally, depends on how we decide to implement it) each time `OrganizationRadiusSettings` emits the signal of `post_save`

This change may require changes in [django-freeradius](https://github.com/openwisp/django-freeradius) too.

**Comment by R9295** [comment]
What's the standard length of the token that Freeradius assigns?

**Comment by rohithasrk** [comment]
@R9295 Check this out https://github.com/openwisp/django-freeradius/blob/master/django_freeradius/apps.py#L16

**Comment by R9295** [comment]
So I'm thinking of something like this for authentication:

``` python
class RadiusTokenAuthentication(TokenAuthentication):
    model = OrganizationRadiusSettings

    def authenticate_credentials(self, token):
        try:
            org = self.model.objects.get(token=token)
        except self.model.DoesNotExist:
            return HttpResponse(status=403)

        if not org.module_active:
            return HttpResponse(status=403)
   
     # return something
```

While going though ``rest_framework``'s code for ```TokenAuthentication```, I saw:
```
    """
    A custom token model may be used, but must have the following properties.
    * key -- The string identifying the token
    * user -- The user to which the token belongs
    """
```
What could be valid to return? I was thinking ```return (org, token)```

I'm referring to this: https://github.com/encode/django-rest-framework/blob/468cdd16edabbb327c7dde877f3b0a18bea082b9/rest_framework/authentication.py#L204

**Comment by nemesisdesign** [comment]
@R9295 see how it's being done on django-freeradius to get inspiration:
https://github.com/openwisp/django-freeradius/blob/ff318850c26ebd6ae2c603b0033b7d010ae5ee87/django_freeradius/api/views.py#L24-L34

In our case I think we should use both UUID and token, otherwise we'll have to make the token field unique.. in openwisp-controller is done in that way but it's quite ugly (and insecure because a member of a different org could in theory accidentally discover that another orgs use a certain token if he gets an error like "an object with this token already exists").

I guess we can simply send both UUID and token in the authorization header, seaparated by space, eg:
```
Authorization: Bearer <UUID> <token>
```
And I guess you will then be able to retrieve it like:
```python
parts = header.split(' ')
try:
    uuid = parts[1]
    token = parts[2]
except IndexError:
   # (we should do this in django-freeradius too..
   # I think if someone tries to send a malformed authorization header
   # the application will return a 500 internal server error)
   pseudocode: return 400
```
