### ISSUE TITLE
[feature] Allow restricting international mobile prefixes allowed to register when SMS verification is enabled

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#160]
Allow restricting international mobile prefixes allowed to register when SMS verification is enabled.

This should be implemented like the freeradius allowed host features.

By default all prefixes are allowed.

**Comment by NoumbissiValere** [comment]
> Allow restricting international mobile prefixes allowed to register when SMS verification is enabled.
> 

@nemesisdesign please I don't understand this well. Do you mean the feature which will be implemented should enable users to restrict international mobile prefixes which by default

**Comment by nemesisdesign** [comment]
> > Allow restricting international mobile prefixes allowed to register when SMS verification is enabled.
> 
> @nemesisdesign please I don't understand this well. Do you mean the feature which will be implemented should enable users to restrict international mobile prefixes from being registered when sms verification is enabled? Please explain more if I'm wrong. Thanks

@NoumbissiValere: when an organization has SMS verification enabled, the [API (via the serializer) will require the phone number of the user during registration](https://github.com/openwisp/openwisp-radius/blob/master/openwisp_radius/api/serializers.py#L264-L289).

Some organizations need to filter out the allowed international prefixes for legal reasons, since some countries allow buying a SIM card without an ID document, therefore they don't want to trust SIMs of those countries, they only want to trust specific countries which require an ID document.

Therefore we need to allow organizations to specify which international prefixes they allow. 
By default, if this is unspecified, all prefixes should be allowed.

We implemented something similar when [restricting the ip addresses from which the freeradius API endpoints can be consumed](https://github.com/openwisp/openwisp-radius/pull/145).

- we should add a global setting for this
- users can override this at organization level using OrganizationRadiusSettings, the freeradius_allowed_ip mechanism can be replicated since it works well
- it shall be possible to leave this setting empty, which means all international prefixes are allowed
- If the model field is filled, it will override what's in the settings

Is it clearer now?
