### ISSUE TITLE
Add more attributes to the tuple of RadiusCheck model

### ISSUE THREAD

**Issue by rohithasrk** [openwisp/openwisp-radius#165]
There are very limited attributes as of now for the RadiusCheck model. We could have additional attributes or add a way to use those additional attributes. Like `Simultaneous-Use` etc. We'll have to research a bit more about this and then proceed. This option exists for the RadiusGroupCheck as of now.

**Comment by nemesisdesign** [comment]
Closing in favor of https://github.com/openwisp/openwisp-radius/issues/336.
