### ISSUE TITLE
[dependencies] Migrate to dj-rest-auth

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#168]
One of the dependencies, [django-rest-auth](https://github.com/Tivix/django-rest-auth), is not actively maintained anymore.

We should switch to the maintained fork: [dj-rest-auth](https://github.com/jazzband/dj-rest-auth).

**Comment by prasenjit** [comment]
I would like to work on this issue.

**Comment by tullur** [comment]
Hello @nemesisdesign , I'll try to do this issue.
