### ISSUE TITLE
[dependencies] freeradius-rest package not found on pfSense (FreeBSD)

### ISSUE THREAD

**Issue by EmadGKamel** [openwisp/openwisp-radius#169]
I'm tring to use openwisp-radius with pfSense firewall which is a FreeBSD-based platform but I can't find freeradius-rest package.
I know that freeradius-rest is not maintained by openwisp team but I'm asking if you can help with a solution.

**Comment by nemesisdesign** [comment]
@EmadGKamel I usually deploy freeradius on a different linux server rather than on pfsense itself. Pfsense just communicates with freeradius using the RADIUS protocol
For further questions please use the [OpenWISP support channels](http://openwisp.org/support.html).
