### ISSUE TITLE
[api] Handle change phone number validation error without marking the user as inactive

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#191]
Follow up to #183. 

When changing the phone number, if the creation of the token fails for some reason, the user will be flagged as inactive even though their number has not been changed.

We can solve this in different ways:

- catch the validation error and set is_active back to True, not really elegant
- allow the creation of phone token objects also for active users, flag the user as inactive only after the token has been created successfully - sounds cleaner

@NoumbissiValere what do you think?

**Comment by NoumbissiValere** [comment]
I love the second point :+1: 
Let me implement it :smile:
