### ISSUE TITLE
[qa] Split huge views and test_api

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#196]
The api views are huge, we should divide the API endpoints dedicated to `freeradius` from the other ones.

The `test_api.py` file is also huge, we should split it in multiple files, if it works we may use a subfolder, eg:

- test_api/test_freeradius_api.py
- test_api/test_registration.py
- test_api/test_rest_token.py
- test_api/test_phone_token.py

We should group related tests in specific files, we should not aim to have too many files, but we should aim to keep the length of each file lower than 1000 lines and ideally lower than 700 lines.

**Comment by devkapilbansal** [comment]
I am working on this
