### ISSUE TITLE
[tests] Hide testing output 

### ISSUE THREAD

**Issue by atb00ker** [openwisp/openwisp-radius#197]
Easy issue for new contributors:

1. Setup the repository
2. Run tests (notice it outputs a lot of things)
3. Checkout the following functions:
- https://github.com/openwisp/openwisp-utils#openwisp_utilstestscapture_stdout
- https://github.com/openwisp/openwisp-utils#openwisp_utilstestscapture_stderr
- https://github.com/openwisp/openwisp-utils#openwisp_utilstestscapture_any_output
4. Use them to suppress the output of the tests.
5. Checkout our commit guidelines: https://openwisp.io/docs/developer/contributing.html
6. Create a pull request.

**Comment by dmanit** [comment]
will do this tomorrow

**Comment by devkapilbansal** [comment]
@atb00ker isn't it similar to #83

**Comment by nemesisdesign** [comment]
> @atb00ker isn't it similar to #83

@devkapilbansal I also think it's a duplicate.

**Comment by atb00ker** [comment]
I didn't see that one.
Let me close it. 😄
