### ISSUE TITLE
[api] Accounting filtering shows "[invalid name]: "

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#20]
How to reproduce the problem:

1. open `http://localhost:8000/api/v1/accounting/?uuid=<uuid-of-org>&token=<token-of-org>`
2. click on "Filters" in the upper right corner
3. notice the last row: `[invalid name]: `

How do we fix that? Could you check if it's happening also in [django-freeradius](https://github.com/openwisp/django-freeradius)? Does it have to be fixed in django-freeradius to be fixed here as well?

**Comment by R9295** [comment]
@nemesisdesign I'll take this one up

**Comment by nemesisdesign** [comment]
@R9295 :+1:

**Comment by R9295** [comment]
It seems that the issue is this field:
https://github.com/openwisp/django-freeradius/blob/master/django_freeradius/api/views.py#L96

If I copy the ```AccountingFilter``` class's code and remove the ```is_open``` filter and then apply it to the inherited view, it last row is removed.
