### ISSUE TITLE
[freeradius] Ensure gracefully error when unique_id is used again mistakenly

### ISSUE THREAD

**Issue by atb00ker** [openwisp/openwisp-radius#216]
When a `unique_id` is is used again by some manual mistake / error, the exception is not caught gracefully.

Reproduce error steps:

1. Create two organizations <org1> and <org2>.
2. Create a user <user1> as a member of <org1> and <org2>.
3. Use API to send accounting  "status_type: start" request from <org1>:
```
curl -X POST http://localhost:8000/api/v1/accounting/ \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer <org1-uuid> <org-token>" \
    -d '{"unique_id": "1", "session_id": "1", "nas_ip_address": "172.16.1.1", "session_time": "1", "input_octets": "1", "output_octets": "1", "username": "user", "status_type": "Start"}'
```
Now, you can stop server with stackoverflow error by sending "status_type: stop" request with same values but from <org2>:
```
curl -X POST http://localhost:8000/api/v1/accounting/ \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer <org2-uuid> <org-token>" \
    -d '{"unique_id": "1", "session_id": "1", "nas_ip_address": "172.16.1.1", "session_time": "1", "input_octets": "1", "output_octets": "1", "username": "user", "status_type": "Stop"}'
```
Or you can cause maximum recursion depth exceeded to spam the server by sending a  "status_type: start" from <org2>:
```
curl -X POST http://localhost:8000/api/v1/accounting/ \
     -H "Content-Type: application/json" \
     -H "Authorization: Bearer <org2-uuid> <org-token>" \
    -d '{"unique_id": "1", "session_id": "1", "nas_ip_address": "172.16.1.1", "session_time": "1", "input_octets": "1", "output_octets": "1", "username": "user", "status_type": "Start"}'
```

**Comment by nemesisdesign** [comment]
@atb00ker is it related to https://github.com/openwisp/openwisp-radius/issues/149? But different right?

**Comment by atb00ker** [comment]
Yes, this one is different.

**Comment by codesankalp** [comment]
I can't reproduce it as mentioned in the issue description.

**Comment by nemesisdesign** [comment]
I confirm what @codesankalp wrote, it somehow got fixed by other changes (and there have been a number of improvements since this issue was opened). Thanks! :+1:
