### ISSUE TITLE
[change] Add model fields to manage fallback values and reuse across models and admin

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#230]
We've been adding different fields to `AbstractOrganizationRadiusSettings` which if NULL default to the value of a specific setting.

We introduced a special admin form field to deal with this case, so we can avoid having to write redundant code like:

```python
if org_settings.api_enabled is not None:
    api_enabled = org_settings.api_enabled
else:
    api_enabled = app_settings.API_ENABLED
```

But this works only in the admin, so in all the non admin code, the redundant and ugly code above is needed.

We should fix this.

We should change the model field to work similarly to the fields used in the admin, I am not 100% sure if the same solution can be reused, maybe, maybe not, we'll have to investigate this. If the same solution can be used, we should just move the fallback fields to their own `fields.py` file and reuse them, then we should clean all the redundant code like the one above (any code that checks if the value is `None` and if its `None` it supplies the fallback setting value)

**Comment by niteshsinha17** [comment]
@nemesisdesign I need some suggestion. 
I am almost there and have implemented the feature using model and its working fine.
But for this -
```api_enabled = org_settings.api_enabled```
I am not sure how to get fallback value in this situation. Is there any method in django that creates fields value? Do you have any idea? I am still trying to find some why.

**Comment by niteshsinha17** [comment]
> @nemesisdesign I need some suggestion.
> I am almost there and have implemented the feature using model and its working fine.
> But for this -
> `api_enabled = org_settings.api_enabled`
> I am not sure how to get fallback value in this situation. Is there any method in django that returns fields value at the time of query? Do you have any idea? I am still trying to find some why.
