### ISSUE TITLE
[feature] Implement explicit identity verification mechanism to allow banning users in OpenWISP RADIUS

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#233]
The current implementation relies on `is_active` for knowing if a user is verified or not, but this prevents us from banning users, because inactive users can verify their mobile phone again.

We need to implement this as it was implemented in OpenWISP1:

- `is_active=False` means the user cannot log in 
- another field will let us know if the user has verified their identity

Therefore an user who has verified their identity but has `is_active=False` has been banned for illicit activity.

## RegisteredUser model

:heavy_check_mark: We should add a new model in openwisp-radius, called `RegisteredUser` which binds one to one with the User model. 

:heavy_check_mark: Records of this DB table will be created only when users self registers via OpenWISP RADIUS.

This model will have the fields described below.

## `identity_verification` field

:heavy_check_mark: `identity_verification`, char field, defaults to NULL, max length 64 characters and will be readonly in the admin. It should be a choice field, but **the choices should be dynamic (eg: returned by a function) and additional choices can be registered via python code like we do with notification types**.

The default choices will be:

:heavy_check_mark:   - No identity verification (default)
:heavy_check_mark:  - Mobile phone

:heavy_check_mark: The identity verification field shall be filled correctly during sign up: if the SMS verification is enabled and the mobile phone is present, the mobile phone option will be chosen, otherwise it will fallback to the default.

## `is_verified` field

:heavy_check_mark: We should also add a boolean field called to this new model, which is called`is_verified` which defaults to False, which tells us if the user has verified their account with one of the accepted identity verification methods.
This flag will have to be set to True once the user completes the verification process (eg: mobile verification with SMS token).

### OrganizationRadiusSettings.needs_identity_verification

:heavy_check_mark: Since the identity verification methods are extensible and we can't know beforehand which ones will be activated, we need a generic way to know if we need to require users to have verified their identity before letting them in. 

For this reason we shall add a boolean field called `needs_identity_verification` to `OrganizationRadiusSettings`, which defaults to `False` but will be set as `True` if `sms_verification` is enabled.
This field shall be implemented exactly as https://github.com/openwisp/openwisp-radius/issues/98, we should have a general setting which can be overridden per org.

Other modules or custom app extending openwisp-radius will also make sure to set it to True when additional identity verification methods are enabled for an org.

## Update the rest of the system accordingly

In order to make these change effective, we will have to update code an tests in the system.

:heavy_check_mark: Here we have to add `RegisteredUser.is_verified=True`:

https://github.com/openwisp/openwisp-radius/blob/79fcc128dd4b4b5c743cfaabf6d61ab2ebd57135/openwisp_radius/api/views.py#L891-L893

https://github.com/openwisp/openwisp-radius/blob/79fcc128dd4b4b5c743cfaabf6d61ab2ebd57135/openwisp_radius/api/views.py#L592

:heavy_check_mark: Here we can use `needs_identity_verification` instead of `sms_verification_enabled`:

https://github.com/openwisp/openwisp-radius/blob/79fcc128dd4b4b5c743cfaabf6d61ab2ebd57135/openwisp_radius/api/serializers.py#L387-L388

:heavy_check_mark: In the following lines we have to replace `is_active` with `RegisteredUser.is_verified`:

https://github.com/openwisp/openwisp-radius/blob/79fcc128dd4b4b5c743cfaabf6d61ab2ebd57135/openwisp_radius/api/views.py#L592

:heavy_check_mark: Here, if identitfy verification is needed, we have to modify the filter to look for verified users, eg:

```python
filter_kwargs = dict(is_active=True)
if org_settings.needs_identity_verification:
    filter_kwargs['registereduser__is_verified'] = True

 user = auth_backend.get_users(username).filter(**filter_kwargs)[0]
```

:heavy_check_mark:
https://github.com/openwisp/openwisp-radius/blob/79fcc128dd4b4b5c743cfaabf6d61ab2ebd57135/openwisp_radius/api/views.py#L237

:heavy_check_mark:

https://github.com/openwisp/openwisp-radius/blob/79fcc128dd4b4b5c743cfaabf6d61ab2ebd57135/openwisp_radius/api/views.py#L629 

:heavy_check_mark:

https://github.com/openwisp/openwisp-radius/blob/79fcc128dd4b4b5c743cfaabf6d61ab2ebd57135/openwisp_radius/api/views.py#L646

:heavy_check_mark: Update the comments:

https://github.com/openwisp/openwisp-radius/blob/79fcc128dd4b4b5c743cfaabf6d61ab2ebd57135/openwisp_radius/api/views.py#L927-L929

:heavy_check_mark: Here we have to make sure that if `needs_identity_verification` is `True`, we also need to check `RegisteredUser.is_verified` before letting the user log in:

https://github.com/openwisp/openwisp-radius/blob/79fcc128dd4b4b5c743cfaabf6d61ab2ebd57135/openwisp_radius/api/views.py#L594

**Comment by Purhan** [comment]
Could this be added to `openwisp-users` instead? Otherwise we'd have to extend the `UserCreationForm` to display this field in the admin.

**Comment by nemesisdesign** [comment]
> Could this be added to `openwisp-users` instead? Otherwise we'd have to extend the `UserCreationForm` to display this field in the admin.

@Purhan I don't think so, because this data is used only in OpenWISP RADIUS and it's meant to be created by the registration API. So there would be no reason to add this to openwisp users.

**Comment by nemesisdesign** [comment]
I have added more details to the issue, including the reasons for which we need to implement this.
I hope is clearer and more detailed now.

**Comment by Purhan** [comment]
@nemesisdesign in places you have mentioned we should use `user.is_verified`. Shouldn't it be `user.registereduser.is_verified` if we are going to use a One to One relationship with `RegisteredUser` model? Just making sure I'm not missing out on anything...

**Comment by nemesisdesign** [comment]
> @nemesisdesign in places you have mentioned we should use `user.is_verified`. Shouldn't it be `user.registereduser.is_verified` if we are going to use a One to One relationship with `RegisteredUser` model? Just making sure I'm not missing out on anything...

Yes you're right @Purhan, let me correct the text.
