### ISSUE TITLE
"SocialApp is not register" fix

### ISSUE THREAD

**Issue by bartolomeoadrian** [openwisp/openwisp-radius#234]
Hi! I was having some trouble starting the server, the next error showed up when i runned
`python3 manage.py migrate`

![image](https://user-images.githubusercontent.com/35029613/107798079-6da51c00-6d3a-11eb-8bc9-6650c263f738.png)

Fixed it by changing this in the file `/user/local/lib/python3.8/dist-packages/openwisp_users/admin.py` - line 630 as the error indicated:

![image](https://user-images.githubusercontent.com/35029613/107797988-4ea68a00-6d3a-11eb-87b6-bb428e471156.png)

To this:

![image](https://user-images.githubusercontent.com/35029613/107798014-56662e80-6d3a-11eb-8e20-109a1e3a1cf2.png)

I dont know if i messed up or fixed something as i dont understand well enough the library but hope it helps someone else because now my server is running just fine

**Comment by Purhan** [comment]
Hey @bartolomeoadrian,

> Fixed it by changing this in the file /user/local/lib/python3.8/dist-packages/openwisp_users/admin.py - line 630 as the error indicated:

Judging by this line, I think you're not running this inside a virtual environment, it is always advisable to use virtual environments for openwisp's modules.
Also, I couldn't replicate this issue in first place, the setup works just fine on master. I think this should be closed for now.

**Comment by nemesisdesign** [comment]
@bartolomeoadrian `/user/local/lib/python3.8/dist-packages/openwisp_users/admin.py` is a file of [openwisp-users](https://github.com/openwisp/openwisp-users), not openwisp-radius.  

How did you install OpenWISP (dev install, ansible-openwisp2, docker-openwisp) and which modules are you using?

**Comment by anish5256** [comment]
@bartolomeoadrian its working fine for me
