### ISSUE TITLE
 Getting errors while registering the Custom User model

### ISSUE THREAD

**Issue by chanduaki** [openwisp/openwisp-radius#238]
# Summary 

Getting errors while registering the Custom User model

```
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/squad/.local/lib/python3.8/site-packages/django_freeradius/admin.py", line 77, in <module>
    admin.site.unregister(user_model)
  File "/home/squad/.local/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 144, in unregister
    raise NotRegistered('The model %s is not registered' % model.__name__)
django.contrib.admin.sites.NotRegistered: The model CustomUser is not registered


```
# What i want to see?
Have to override the User with CustomUser

# What i was see?
Getting errors in the site package

**Comment by nemesisdesign** [comment]
@chanduaki why are you using django-freeradius, which is discontinued?
Did you know that? Have you read here? https://github.com/openwisp/django-freeradius#django-freeradius

See also:

- how to extend openwisp radius: https://openwisp-radius.readthedocs.io/en/latest/developer/how_to_extend.html
- custom user model using openwisp-users as a base: https://github.com/openwisp/openwisp-users
- working code example: https://github.com/openwisp/openwisp-radius/blob/master/tests/openwisp2/sample_users/models.py

The information you provided is not enough to conclude there is a bug.
Please use the general chat for support questions and leave the github issue tracker only for bug reports.
If you think there is a bug, we need to replicate the bug in the test environment of openwisp-radius, but as I mentioned in the bullet list above, there's a working custom user model in the test env of this project.
