### ISSUE TITLE
[batch] Batch users do not get the organization

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#24]
Users created with batch operations from the admin must be created as members of the same organization  which was used to create the batch operation object, at the moment they get no organization.

It seems that this is being done for the API but the feature has to be unit tested.

**Comment by R9295** [comment]
@nemesisdesign I'd like to take this up.

**Comment by nemesisdesign** [comment]
@R9295 go ahead :+1:
