### ISSUE TITLE
[deps] dj-rest-auth==2.1.6 breaks build

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-radius#266]
URL encoding in https://github.com/iMerica/dj-rest-auth/commit/1f28787c7d137f20404b7218bfcf9d31d38cb266 was modified in dj-rest-auth. This breaks the following test

https://github.com/openwisp/openwisp-radius/blob/61ad2bdc1f6230746a37008914d2f34a4ea1227c/openwisp_radius/tests/test_api/test_api.py#L605-L615

**Comment by nemesisdesign** [comment]
Please send a patch to master.
