### ISSUE TITLE
[batch] Add unit test for batch creation operation performed via API

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#27]
A unit test should check that the API view of the batch user creation operation assigns created users to the right organization.

**Comment by Vivekrajput20** [comment]
I would like to work on it @nemesisdesign

**Comment by nemesisdesign** [comment]
@Vivekrajput20 sure, go ahead :+1:

**Comment by ankit-kumar-dwivedi** [comment]
@Vivekrajput20 are you still working on this issue?

**Comment by Vivekrajput20** [comment]
I have already made a PR @ankit-kumar-dwivedi .
