### ISSUE TITLE
[feature] Add management command and celery task to delete unverified users

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#279]
This was a feature that was previously used in OpenWISP1, certain type of unverified users were removed automatically.

We should replicate the same, following something similar to what we did previously, see:
https://github.com/openwisp/openwisp-radius/blob/211c30cd1d249acb73619c2a39a77a2f6324d500/openwisp_radius/tasks.py

The new command shall look for users which have a RegisteredUser relation and RegisteredUser.is_verified=False and have been created for more than X days ago, where days is is a parameter defaulting to 1 day (24 hours).

The command shall accept an `exclude_methods` parameter which can contain a list of verification methods to exclude from the query, so that certain verification methods can be excluded and not deleted anyway.

The command shall be documented as the other ones.

**Comment by pandafy** [comment]
> The command shall accept an exclude_methods parameter which can contain a list of verification methods to exclude from the query, so that certain verification methods can be excluded and not deleted anyway.

Do you mean registration method here?
