### ISSUE TITLE
[change/fix] Update username when phone number is changed

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#282]
In the following view:

https://github.com/openwisp/openwisp-radius/blob/2465d6f0b367aa5fba70eb67b2e7d905ac66ef8f/openwisp_radius/api/views.py#L580-L588

There's a corner case to handle.
When using mobile phone verification, the username is set to be the same as the phone number.
So when the phone number is updated right now the username remains the old phone number.

We should add some logic to handle this corner case, it's not the cleanest solution but we can improve this in the future.
We can look if the old phone number is the same as the username and in that case I would update the username as well.

**Comment by pandafy** [comment]
I was unable to find existing tests for cases where user registers with only `phone_number`(without `username`). Upon further investigation of code, I found that username is required field in for Register Serializer. 

Using phone_number as username is done in openwisp-wifi-login pages and not in this repository. 

https://github.com/openwisp/openwisp-wifi-login-pages/blob/4afc5ac2f5880bcaf4aa0344e8f177a55424708c/client/components/registration/registration.js#L149-L153

So, should we make this change here?
