### ISSUE TITLE
[bug] Make  "is_sms_verification_enabled" respect global settings

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-radius#301]
I have done some similar work in https://github.com/openwisp/openwisp-radius/pull/300 for `registration_enabled` which can be used as reference. 

https://github.com/openwisp/openwisp-radius/blob/602f3ecf357c3b4ecba0a60dabedd6f9c28f1319/openwisp_radius/base/models.py#L1142-L1145

https://github.com/openwisp/openwisp-radius/blob/602f3ecf357c3b4ecba0a60dabedd6f9c28f1319/openwisp_radius/api/utils.py#L55-L62

**Comment by iamvaishnav** [comment]
I'd like to work on this.

**Comment by pandafy** [comment]
@iamvaishnav you may go ahead on this! Feel free to ask for help here or on [OpenWISP's general chat](https://gitter.im/openwisp/general).
