### ISSUE TITLE
[change] API: radiusbatch endpoint URL not consistent

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#302]
The radiusbatch endpoint URL is not consistent, it should be `/api/v1/radius/batch/`, we can introduce a backward incompatible change in this case since this endpoint is used rarely and scripts using it can update the URL easily.
Docs shall be updated as well.

Let's change also `/radius/organization/{slug}/radiusbatch/{id}/pdf/` to `/radius/organization/{slug}/batch/{id}/pdf/`.

**Comment by atharmohammad** [comment]
Hey @codesankalp , are you working on this ? i would like to work on it if issue is available

**Comment by nemesisdesign** [comment]
> Hey @codesankalp , are you working on this ? i would like to work on it if issue is available

Go ahead, @atharmohammad, @codesankalp will help with reviewing and testing.

**Comment by atharmohammad** [comment]
> > Hey @codesankalp , are you working on this ? i would like to work on it if issue is available
> 
> Go ahead, @atharmohammad, @codesankalp will help with reviewing and testing.

okay , on it
