### ISSUE TITLE
[change] Allow enabling/disabling registration methods (SAML, Social login, SMS)

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#308]
We should add a way to allow users to specify if they want to enable specific registration/login methods like SAML, social login, SMS verification, etc. for their organization.

We shall also check if a method it's enabled before allowing users to log in / sign up with it or otherwise return 403.

**Comment by atharmohammad** [comment]
@nemesisdesign  can we add a boolean field ```social_login```  like ```sms_verification``` in organisation settings and see if social_login is enabled else we raise permission denied ? is this a correct approach to the issue else can you provide me some insights on what could be done ?

**Comment by nemesisdesign** [comment]
> @nemesisdesign can we add a boolean field `social_login` like `sms_verification` in organisation settings and see if social_login is enabled else we raise permission denied ? is this a correct approach to the issue else can you provide me some insights on what could be done ?

We are not sure yet, but let's keep it open until we find out what's the best way to handle this.
