### ISSUE TITLE
[Bug] Unable to Login into Django Admin with Host Address

### ISSUE THREAD

**Issue by chanduaki** [openwisp/openwisp-radius#311]
**Steps to reproduce:**

   - Install the master branch code
   - change the django settings( ALLOWED_HOSTS = ["*"]
    OPENWISP_RADIUS_FREERADIUS_ALLOWED_HOSTS = ['IP Address','IP Address'
    ])
   - Create a superuser ( python3 manage.py createsuperuser)
  -  Login with (http://ipaddress:8000/admin)
  -  It will be in the same page|
  
https://files.gitter.im/59108303d73408ce4f5de0c9/a41y/image.png

**Comment by pandafy** [comment]
Are you using the test project? Compare settings.py of your project with [/tests/openwisp2/settings.py](https://github.com/openwisp/openwisp-radius/blob/master/tests/openwisp2/settings.py).

**Comment by chanduaki** [comment]
@pandafy 
Yes, using the Test project 
Settings are same

**Comment by chanduaki** [comment]
@pandafy 

Able to login with `localhost ` and `127.0.0.1`
![image](https://user-images.githubusercontent.com/54622987/135642572-59f6051c-48ea-4147-98c7-c974ab38108f.png)

when i am trying to login with IP Address -> Same it was going to login page again (BUG) - May be redirection is not properly done

with IP Address -> Forgot password is working 

Can you please check once

**Comment by pandafy** [comment]
Have you tried this https://groups.google.com/g/django-users/c/HHtoOC3cI3k?

**Comment by chanduaki** [comment]
Its tried in a freshly installed system and those are new VMs
Also there are no `*.pyc files` in project , and tried to delete the database and tried 

Couldnt identified the core issue

**Comment by chanduaki** [comment]
Thankyou for you support @pandafy 

**Solution:**
commented out the 'SESSION_COOKIE_SECURE' and
'SESSION_EXPIRE_AT_BROWSER_CLOSE' from the settings.py file. 

This solved my issue

**Comment by pandafy** [comment]
Glad to hear that! Kindly use [OpenWISP's support channels](https://openwisp.org/support.html) for your queries next time since this is our issue tracker.
