### ISSUE TITLE
[change!] Remove customization for checks and replies

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#336]
The following customizations for check and replies are no longer maintained by the contributor who originally added them:

- is_active field
- valid_until field
- choices for attribute
- logic which implements password field in the admin
- documentation mentioning these features

I am not aware of anyone else using it and I think are overkill to keep in the core of OpenWISP RADIUS.
Since these customizations can be implemented by extending/forking OpenWISP RADIUS, we should remove these to reduce maintenance overhead.

The choice field on the attribute field also limits the flexibility of the checks/replies.

**Comment by iamvaishnav** [comment]
I'd like to work on this.

**Comment by devkapilbansal** [comment]
@iamvaishnav go ahead

**Comment by nemesisdesign** [comment]
There were a few missing things, I handled it in https://github.com/openwisp/openwisp-radius/commit/56cf9f15a56808fa593e38a33f60bc2221d4f768.
