### ISSUE TITLE
[docs] Fix internal references

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#339]
In the docs we have quite a few internal references which point to HTML pages, but that doesn't work well when the documentation is converted to non HTML formats (eg: PDF, ePub). We should change those references to use the [ReStructuredText format for internal references](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/references.html#use-a-custom-anchor), eg:

```
:ref:`configure-rest-module`
```

**Comment by SwastikTripathi** [comment]
Hi @nemesisdesign! We can use  `:ref:`Cross-References to Locations in the Same Document``  to link to internal headings.
Should we some simple regex substitutions.
Can you assign me this?

**Comment by nemesisdesign** [comment]
> Hi @nemesisdesign! We can use `:ref:`Cross-References to Locations in the Same Document`` to link to internal headings. Should be some simple regex substitutions. Can you assign me this?

Sure, you can proceed.
Look at how it's done in this PR: https://github.com/openwisp/openwisp-radius/pull/334/files#diff-8a2f1810bbd4a1d7eb1dee7be03d83ae53f10700df153e6fffcc510f37956ac9R89 (look for `:ref:`).
Thanks.

**Comment by SwastikTripathi** [comment]
I'm sorry @nemesisdesign , but I can't do this. I just can't seem to get around restructured text.
Please unassign me.

**Comment by unnati914** [comment]
Hi.. I am interested to work on this. Could I work if no one is working on this?
Thanks

**Comment by pandafy** [comment]
You can go ahead on this @unnati914!

**Comment by nemesisdesign** [comment]
@unnati914 I did some work on this which you can use as reference:
https://github.com/openwisp/openwisp-radius/commit/16c0ecfca786666b5aa0a5a57816c24e4caaa2fe

I was improving the text so I also took advantage to fix some references.

**Comment by unnati914** [comment]
surely, I will firstly try to set it up locally and try, after that I will push it :)

**Comment by prathamaror** [comment]
can i start working on this issue as well

**Comment by pandafy** [comment]
Sure @prathamaror! 
@unnati914 I hope you are not working on this anymore (?)

**Comment by unnati914** [comment]
yes I am not working on this

**Comment by Aryamanz29** [comment]
Hey @prathamaror , Are you working on this?

**Comment by prathamaror** [comment]
Hey, yes yes I am currently working on this issue it is taking a bit longer
then excepted but it will soon be done
