### ISSUE TITLE
[bug] invalid username allowed

### ISSUE THREAD

**Issue by atb00ker** [openwisp/openwisp-radius#365]
Create a batch of users (`/radiusbatch/add/`) using prefix method, and set the name and prefix as `Test#1` and save the batch.
Notice that the username `Test#1` is not allowed hence the request fails.

We should add a check in the input boxes to ensure only valid characters for username are allowed.

**Comment by bsande6** [comment]
@atb00ker Hey, I am new to open source and would like to contribute. Can I give this issue a shot?

**Comment by atb00ker** [comment]
@bsande6 feel free to start with it, permission not required! :smile:

**Comment by bsande6** [comment]
@atb00ker Great! May I be assigned to this issue?

**Comment by atb00ker** [comment]
Hi @bsande6 please start working on it, no assignment, permission or any process such is required to contribute.
When you create the pull request, please tag me for review! :smile:

**Comment by bsande6** [comment]
@atb00ker I have followed the setup steps and have been able to launch the server on localhost however any changes I make in the code are not being displayed on the localhost. Do you have any ideas on where I have gone wrong?

**Comment by atb00ker** [comment]
@bsande6 
Please ask questions in the development channel : https://gitter.im/openwisp/development
From the information provided, I have no clue.
Please add more details in the gitter channel about the change that you are making and it's not reflecting! 😄
