### ISSUE TITLE
[docs] Iinstalling issue on ubuntu 20

### ISSUE THREAD

**Issue by B14ckP4nd4** [openwisp/openwisp-radius#378]
Hi there

I try to install OpenWisp and FreeRadius on ubuntu 20 based on openwisp docs

now openwisp is installed but there is an issue with installing steps of freeradius 3

at this step : apt-add-repository ppa:freeradius/stable-3.0  ( https://launchpad.net/~freeradius/+archive/ubuntu/stable-3.0 )
for installing freeradius 3 stable this repo was already deprecated so I try the alternative way suggested by launchpad ( http://packages.networkradius.com/ )

now,  I got this error when I try to install : 
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://packages.networkradius.com/freeradius-3.0/ubuntu/focal focal InRelease' doesn't support architecture 'i386'

what should I do now?  is there any updated documentation for installing on ubuntu 20 or what is the comfortable distro and version for this configuration?

**Comment by nemesisdesign** [comment]
See https://networkradius.com/packages/
