### ISSUE TITLE
Release Schedule

### ISSUE THREAD

**Issue by bmarika** [openwisp/openwisp-radius#393]
Thank you all for this awesome project.

Going through the project, I found out that the last release was in 2020.  Should we release the latest master to pypi?

Asking this as I faced an issue with base64 encoding which has been fixed [here]( https://github.com/openwisp/openwisp-radius/issues/287) but not yet released.

**Comment by nemesisdesign** [comment]
[We're working on it](https://github.com/openwisp/openwisp-radius/issues?q=is%3Aopen+is%3Aissue+milestone%3A%220.3+release%22),

This is a bug tracker, for support questions please use te [support channels](https://openwisp.org/support.html).

**Comment by nemesisdesign** [comment]
The new release is out: https://openwisp-radius.readthedocs.io/en/latest/general/changelog.html.
