### ISSUE TITLE
[bug] FallbackTextField does not handle empty strings

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-radius#435]
If the value of the of `FallbackTextField` is an empty string (`''`), then the form field does not show the fallback value. We should check the TextField for falsy values, i.e. for both `None` and empty string (`''`)

_Originally reported in https://github.com/openwisp/openwisp-radius/pull/433#pullrequestreview-1093123537_

**Comment by nemesisdesign** [comment]
I would double check this on char fields too.
