### ISSUE TITLE
[release] Release 1.0.2

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#457]
Backport the latest fixes and release version 1.0.2.

PS: I have already backported the fixes from master but it's better to double check.

**Comment by pandafy** [comment]
@nemesisdesign https://github.com/openwisp/openwisp-radius/commit/8ecacb7ccbb1db4e2d28570e5fb2c1976c98e6a7 is not present on the 1.0 branch. I checked locally and 1.0.1 contains this bug. I think we should include this patch in 1.0.2

**Comment by nemesisdesign** [comment]
> @nemesisdesign [8ecacb7](https://github.com/openwisp/openwisp-radius/commit/8ecacb7ccbb1db4e2d28570e5fb2c1976c98e6a7) is not present on the 1.0 branch. I checked locally and 1.0.1 contains this bug. I think we should include this patch in 1.0.2

Thanks for catching this, please proceed!
