### ISSUE TITLE
[change] Migrate to openwisp-users REST API filters

### ISSUE THREAD

**Issue by nemesifier** [openwisp/openwisp-radius#473]
Replace plain django-filters with the multi-tenant capable filters being added in https://github.com/openwisp/openwisp-users/pull/347 (once this is merged).

**Comment by pandafy** [comment]
We use `django-filters` on only two API views in openwisp-radius
- `AccountingView`
https://github.com/openwisp/openwisp-radius/blob/265f88a90366823ceb03e60d530ba122f7c054a7/openwisp_radius/api/freeradius_views.py#L392-L410

![Screenshot from 2023-06-26 23-09-59](https://github.com/openwisp/openwisp-radius/assets/32094433/d23cbf6c-4dcf-443d-8d50-cca0bf8f6b6f)


- `UserAccountingView`
https://github.com/openwisp/openwisp-radius/blob/265f88a90366823ceb03e60d530ba122f7c054a7/openwisp_radius/api/views.py#L417-L424

![Screenshot from 2023-06-26 23-10-46](https://github.com/openwisp/openwisp-radius/assets/32094433/83d88587-fe72-491d-817f-826a3be5c6c4)


None of filters provides choices that should be filtered by the user's organization.

**Comment by nemesifier** [comment]
Thanks @pandafy, I am closing this.
