### ISSUE TITLE
[change] Change name of delete_old_users command to reflect its functionality accurately

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-radius#496]
**Current Behavior:**
The `delete_old_users` command deletes users created using RadiusBatch, which might be confusing as it implies a broader functionality than it actually has.

Proposed Change:
Consider changing the name of the `delete_old_users` command to something more specific that accurately reflects its functionality, such as `delete_old_radiusbatch_users`. This would help users understand the purpose of the command more clearly.

Update the documentation if required.

**Comment by namrata18s** [comment]
@pandafy I can work on this issue

**Comment by praptisharma28** [comment]
Hey @pandafy , I am working on this issue. Will do a PR soon. Thankyou!

**Comment by pandafy** [comment]
You can find all occurrences of `delete_old_users` by doing a project-wide search like this https://github.com/search?q=repo%3Aopenwisp%2Fopenwisp-radius%20delete_old_users&type=code

**Comment by praptisharma28** [comment]
Thankyou @pandafy for the help, I just did a PR after the change: https://github.com/openwisp/openwisp-radius/pull/498 . Please have a look at it.

**Comment by namrata18s** [comment]
is this issue still open?

**Comment by pandafy** [comment]
> is this issue still open?

I believe @praptisharma28 is still working on this.

**Comment by praptisharma28** [comment]
Hey @pandafy , I did a PR. Federico said he will review it. I changed the commit name too. And if all the changes done are fine then you can merge it.
https://github.com/openwisp/openwisp-radius/pull/498
