### ISSUE TITLE
[bug] Adding OrganizationUser and assigning default RadiusGroup together raises server error

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-radius#507]
**Steps to replicate**

1. Create a new user at `/admin/openwisp_users/user/add/` (do not add this user to any organization)
2. Edit this user: add organization user with "default" org and add "default-users" Radius user group to this user 
3. Save the user 

**Expected user**

The save operation is performed without any error. The OrganizationUser and RadiusUserGroup objects get created. 

**Actual outcome**

The application raises server 500 error.

**Possible solution**
1. Add a failing test case in https://github.com/openwisp/openwisp-radius/blob/master/openwisp_radius/tests/test_users_integration.py which emulates the above scenario
2. Fix the signal receiver to log this error as warning and return silently 

https://github.com/openwisp/openwisp-radius/blob/3deb0ef8a1e933372e10c1183794b9d9d8fe057b/openwisp_radius/receivers.py#L33C1-L48C22

**Comment by d1vyanshu-kumar** [comment]
can u please assign this issue to me?

**Comment by samirgorai** [comment]
#509
