### ISSUE TITLE
[requirements] Update dependencies & django to 2.2

### ISSUE THREAD

**Issue by atb00ker** [openwisp/openwisp-radius#59]
1. We need to update all the dependencies.
2. Add support for django 2.2
3. Add support / tests for python 3.6 & 3.7

**Comment by udaykiranreddykondreddy** [comment]
@atb00ker can I work on this?

**Comment by atb00ker** [comment]
Hello @udaykiranreddykondreddy 
Sorry, this issue is reserved for GCI event and is not open to be solved right now! :smile:

**Comment by udaykiranreddykondreddy** [comment]
@atb00ker My bad, I thought GCI as something else. Is there any possibility to become a mentor for these projects.

**Comment by atb00ker** [comment]
@udaykiranreddykondreddy 

Please read https://groups.google.com/forum/#!topic/openwisp/IVyjBQlDbxA

**Comment by nemesisdesign** [comment]
Only python 3 is supported in this module, we can test using python 3.6 and 3.7, we should add support for django 3.0.

**Comment by oltarzewskik** [comment]
> we should add support for django 3.0.

In 2 PRs or 1 would be enough?

**Comment by atb00ker** [comment]
> 
In 2 PRs or 1 would be enough? (1 one for dependencies and django 2.2 and second one for django 3.0)

Yes, 2 different pull requests.
