### ISSUE TITLE
Radius token for initial default org not created

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#71]
It seems to me that the `OrganizationRadiusSettings` object (and relative secret token) is not being created for the default organizaiton.

Write a test which fails if the default org does not have a related `OrganizationRadiusSettings` created.

Let the test fail, then add the logic to create it in the `add_default_organization` function (which is called during the first DB migration).

**Comment by atb00ker** [comment]
@nemesisdesign In relation to this, should the behaviour `docker-openwisp` should be that freeradius should work out of the box? 
Currently, unless you add the default organization to a radius group and generate a token manually, the freeradius container doesn't work!

**Comment by nemesisdesign** [comment]
@atb00ker yes I think is good to include it out of the box, it's an easy issue to fix and we'll fix it soon
