### ISSUE TITLE
[requirements] unable to install openwisp-radius

### ISSUE THREAD

**Issue by atb00ker** [openwisp/openwisp-radius#73]
Error: 
```
(openwisp-radius) $ pip install -r requirements.txt --upgrade
 
ERROR: Could not find a version that satisfies the requirement django-freeradius<0.2.0 (from -r requirements.txt (line 1)) (from versions: 0.1a0)
ERROR: No matching distribution found for django-freeradius<0.2.0 (from -r requirements.txt (line 1))
```
Even the travis on openwisp-radius doesn't use `requirements.txt`, which I think it should before installing anything from github/master!

**Comment by 2stacks** [comment]
Have you reviewed - [openwisp/django-freeradius] [docs] Add step to install Weasy Print (#261)?  Need to make sure we aren't still missing dependencies for WeasyPrint.

**Comment by nemesisdesign** [comment]
Now that we don't depend on django-freeradius anymore we won't have this issue.
