### ISSUE TITLE
[radius/api] Use bearer token for user authentication

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#91]
Use `openwisp_users.authentication.BearerAuthentication` instead of `rest_framework.authentication.TokenAuthentication`.

Update documentation to mention this.

This app will have to be upgraded to support this change: https://github.com/openwisp/openwisp-wifi-login-pages

**Comment by Vivekrajput20** [comment]
@nemesisdesign  I think as long as authentication API is returning the new token, we will not have to upgrade  https://github.com/openwisp/openwisp-wifi-login-pages

**Comment by nemesisdesign** [comment]
> @nemesisdesign I think as long as authentication API is returning the new token, we will not have to upgrade https://github.com/openwisp/openwisp-wifi-login-pages

@Vivekrajput20 thanks, I think we will have to update the authorization header, which now should be `Authorization: Token <token>` to `Authorization: Bearer <token>`
