### ISSUE TITLE
[radius/docs] Prepare docs for comprehensive documentation site

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#93]
Prepare the docs for this: https://github.com/openwisp/openwisp2-docs/issues/107
Do this before publishing the docs on readthedocs.org.

**Comment by nemesisdesign** [comment]
@atb00ker can you help with this? It should be pretty quick.
We just need to divide the files which mainly explan how to use the features (`user` dir) from 
the files aimed at developers ('developer' ) and general pages like project goals go to `general`.

This will prepare the way for https://github.com/openwisp/openwisp2-docs/issues/107, but it also allows us to publish the doc now without fear of generating 404 later because we move stuff.

**Comment by atb00ker** [comment]
I am little confused about `api.rst`; it's feature explanation useful only for developers (even people who attach it to captive portal would be developers), so it goes in developer, right?

Here is the list:
```
   /developer/setup
   /user/settings
   /developer/freeradius
   /user/management_commands
   /user/importing_users
   /user/generating_users
   /user/enforcing_limits
   /developer/registration
   /developer/social_login
   /developer/api
   /developer/how_to_extend
   /general/contributing
   /general/goals
```

**Comment by nemesisdesign** [comment]
> I am little confused about `api.rst`; it's feature explanation useful only for developers (even people who attach it to captive portal would be developers), so it goes in developer, right?
> 
> Here is the list:
> 
> ```
>    /developer/setup
>    /user/settings
>    /developer/freeradius
>    /user/management_commands
>    /user/importing_users
>    /user/generating_users
>    /user/enforcing_limits
>    /developer/registration
>    /developer/social_login
>    /developer/api
>    /developer/how_to_extend
>    /general/contributing
>    /general/goals
> ```

User docs are all the explanations of how the application can be used, I think API is part of this.
Developer docs are all the explanations aimed at people which will do development, eg:  contributors, system integrators or people extending openwisp.
