### ISSUE TITLE
[feature] Allow to disable the register API endpoint

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-radius#98]
### Premise

Before working on this, please see how similar features were implemented:

- https://github.com/openwisp/openwisp-radius/issues/96
- https://github.com/openwisp/openwisp-radius/issues/160
- https://github.com/openwisp/openwisp-radius/issues/219

For similar features I mean:

- having a global setting in settings.py
- having a setting for each org in the database, editable via admin interface, this field defaults to NULL and falls back to the global default unless explicitly modified by the org admins 

### Use case

There may be cases in which some or all the organizations using the system may not want to allow users to register accounts.

### 1 step: add a global setting

Add a new setting in settings.py to control whether the registration API is enabled or not at a global level.

The setting will default to True (enabled).

Make sure to document this setting.

### 2 step: OrganizationRadiusSettings

Add a boolean field which indicates whether the registration API is enabled or not.
The boolean can have one of the following values:

- NULL: this is the default
- true: enabled
- false: disabled

Make sure the API view code checks this, if the API endpoint is disabled the API shall return 403.

This needs automated tests.

### Docs

Need to be documented:

- the settings must be listed in the settings page but also mentioned and linked from the API page
- the OrganizationRadiusSettings can be documented in the API page (add a screenshot please)

**Comment by Purhan** [comment]
Working on this :)

**Comment by Purhan** [comment]
> ### 2 step: OrganizationRadiusSettings
> 
> Add a boolean field which indicates whether the registration API is enabled or not.
> The boolean can have one of the following values:
> 
>     * NULL: this is the default
> 
>     * true: enabled
> 
>     * false: disabled

Why does it have to be `NULL` in the admin if it defaults to `True` anyways? I'm not able to understand.

**Comment by Purhan** [comment]
> ### 2 step: OrganizationRadiusSettings
> 
> Add a boolean field which indicates whether the registration API is enabled or not.
> The boolean can have one of the following values:
> 
>     * NULL: this is the default
> 
>     * true: enabled
> 
>     * false: disabled

@nemesisdesign  Why does it have to be `NULL` in the admin if it defaults to `True` anyways? I'm not able to understand.@
